import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.Vector;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    List<Integer> a = new ArrayList<Integer>();
    
    public  static void main(String[] args) {
    	whyVector();
    }
    
    static public void noVector() {
    	Scanner s = new Scanner(System.in);
    	String v1, v2, v3, v4;
    	v1 = s.next(); // read a space-delimited word
    	v2 = s.next();
    	v3 = s.next();
    	v4 = s.next();
    	
    	System.out.print(v1+v2+v3+v4);
    }
    
    static void whyVector() {
    	Scanner s = new Scanner(System.in);
    	Vector data;
    	// allocate vector for storage
    	data = new Vector();
    	// read strings, adding them to end of vector, until eof
    	while (s.hasNext())
    	{
    		String st = s.next();
    		if(st.equals("#")) break;
    		data.add(st);
    	}
    	
    	System.out.print(data);
    }
}
